language: php
php:
    - '7.1'
install:
    - composer require squizlabs/php_codesniffer
script:
    - vendor/bin/phpcs --standard=PSR2 --ignore=*/Tests/* src/AppBundle/
notifications:
    email:
        - aurelien@wildcodeschool.fr
        - akyoswcs@gmail.com
