<?php

namespace AppBundle\Repository;

/**
 * CommunsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunsRepository extends \Doctrine\ORM\EntityRepository
{
}
