<?php

namespace AppBundle\Repository;

/**
 * CondominiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondominiumRepository extends \Doctrine\ORM\EntityRepository
{
    public function createAlphabeticalQueryBuilder()
    {
        return $this->createQueryBuilder('condominium')
            ->orderBy('condominium.name', 'ASC');
    }
}
