<?php

namespace AppBundle\Repository;

/**
 * InterventionSheet
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionSheet extends \Doctrine\ORM\EntityRepository
{
}
