<?php

namespace AppBundle\Repository;

/**
 * Intervention
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Intervention extends \Doctrine\ORM\EntityRepository
{
}
