<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Condominium;
use AppBundle\Entity\Syndicate;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySyndicate(Syndicate $syndicate)
    {
        return $this->createQueryBuilder('i')
            ->join('i.condominium', 'condo')
            ->join('condo.syndicate', 's')
            ->where('s.id = :syndicateId')
            ->setParameter(':syndicateId', $syndicate->getId())
            ->getQuery()
            ->getResult()
            ;
    }


    public function findBySyndicateAndDate(Syndicate $syndicate, \DateTime $date)
    {
        return $this->createQueryBuilder('i')
            ->join('i.condominium', 'condo')
            ->join('condo.syndicate', 's')
            ->where('s.id = :syndicateId')
            ->andWhere('i.interventionDate = :date')
            ->setParameter(':syndicateId', $syndicate->getId())
            ->setParameter(':date', $date)
            ->getQuery()
            ->getResult()
            ;
    }

    public function findBySyndicateProgress(Syndicate $syndicate, string $progress)
    {
        return $this->createQueryBuilder('i')
            ->join('i.condominium', 'condo')
            ->join('condo.syndicate', 's')
            ->where('s.id = :syndicateId')
            ->andWhere('i.progress = :progress')
            ->setParameter(':syndicateId', $syndicate->getId())
            ->setParameter(':progress', $progress)
            ->getQuery()
            ->getResult()
            ;
    }
}