<?php

namespace AppBundle\Repository;

/**
 * SyndicateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyndicateRepository extends \Doctrine\ORM\EntityRepository
{
}
