<?php

namespace AppBundle\Repository;

/**
 * SyndicatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyndicatRepository extends \Doctrine\ORM\EntityRepository
{
}
