<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Building;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends \Doctrine\ORM\EntityRepository
{

    public function findUnitByBuilding($buildingId)
    {
        return $this->createQueryBuilder('u')
            //TODO
            ->andWhere('unit.building = :building_id')
            ->setParameter('building_id', $buildingId)
            ->getQuery()->getResult();
    }
}
